Adding User Group digital artifact
d3fend/d3fend-ontology pull request #159
Opened 2023-04-27 18:17 UTC by ryantxu1

Addresses #154 

Few things I'm open to changing:
1. Placement under 'Access Control Configuration'
2. Properties of 'may contain' Access Control List and Group Policy

@netfl0 @hack-sentinel

2023-04-27 18:46 UTC, ryantxu1 commented
I like these!

2023-04-28 17:14 UTC, ryantxu1 commented
updates made @netfl0 @hack-sentinel

2023-04-28 17:59 UTC, netfl0 requested changes

2023-04-28 17:59 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +    rdfs:subPropertyOf :runs ;
this should be associated-with, not runs

2023-04-28 18:48 UTC, merged