Add Data and Data Type artifact
d3fend/d3fend-ontology pull request #190
Opened 2023-06-21 19:19 UTC by ryantxu1

Addresses #174

2023-06-21 19:22 UTC, ryantxu1 commented on src/ontology/d3fend-protege.ttl
> +        :Structure,
@netfl0 I think this line is the only line that looks a little strange to me, Trying to convey that a Windows Registry **is a** type of the Structure Data Type.

2023-07-10 13:40 UTC, ryantxu1 commented
@netfl0 Are there any other additions that need to be made here?

2023-07-12 11:37 UTC, netfl0 commented
Need to merge develop into this branch, and see my comment on redundant subclass.

2024-08-22 13:24 UTC, netfl0 requested changes

2024-08-22 13:27 UTC, netfl0 commented
> @netfl0 where is your redundant subclass method?

my review was in draft, apologies:

https://github.com/d3fend/d3fend-ontology/pull/190#discussion_r1238641366

2024-12-17 22:20 UTC, netfl0 commented
@ryantxu1 , lets remove registry stuff from this and consider spiffing up the data type taxonomy w/ @aamedina and @hack-sentinel .

2025-04-17 17:00 UTC, closed without merging