New evict and recover techniques
d3fend/d3fend-ontology pull request #240
Opened 2024-05-01 18:50 UTC by ryantxu1

2024-05-01 18:50 UTC, ryantxu1 commented
@netfl0 STILL WIP! But if time allows, please review to see if I'm on the right track

2024-05-02 18:48 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> -:CredentialEviction a :CredentialEviction,
This should definitely remain. Think in terms of a proper taxonomy versus what the matrix looks like.

2024-05-07 15:30 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +:BlackHole a :BlackHole,
Might want to use BlackHole**Route**

2024-05-07 15:32 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +:RemoveRegistryKey a owl:Class,
should be DeleteRegistryKey

2024-05-07 15:32 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +:RemoveUserAccount a owl:Class,
Should be delete

2024-05-07 15:35 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +    rdfs:subClassOf :DigitalInformationBearer ;
should rather be a sublcass of d3f:UserAccount

2024-08-02 18:02 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +:BlackHoleRoute a :BlackHoleRoute,
This might be its own taxonomy. Sometimes you might route for more monitoring/inspection.

2024-08-02 18:13 UTC, netfl0 requested changes
Need feedback from others listed.

2024-08-02 18:13 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +:ObjectEviction a :ObjectEviction,
We DO need a broader category like this, Object is something specific in CCO however. Would like to get thoughts from @hack-sentinel @giacomodecolle  and @johnbeve

Object will resonate with practitioners but has ontological issues.

We already use "Decoy Object", but I am deciding if we want to exacerbate this or move in another direction.

2024-08-04 10:38 UTC, giacomodecolle commented on src/ontology/d3fend-protege.ttl
> +:ObjectEviction a :ObjectEviction,
Yes, "object" is a material entity in BFO/CCO. Have you considered using two labels, one for practitioners and one for ontologists? I think @johnbeve usually recommends prefLabel or altLabel. 

Then we can also start thinking about a corresponding CCO mapping and label (e.g. "malicious information entity eviction").

2024-08-08 17:00 UTC, ryantxu1 commented on src/ontology/d3fend-protege.ttl
> +:ObjectEviction a :ObjectEviction,
@hack-sentinel @netfl0 I guess this is also related to how the current "Restore" tactic is set up since it has a "Restore Object" bucket. Personally, I'm in favor of this because otherwise we get into a situation where there are potentially too many buckets (Evict Hardware Object, Evict Software, etc)

What do yall think? Maybe we can use "Evict ARTIFACT" instead?

2024-08-08 17:13 UTC, ryantxu1 commented on src/ontology/d3fend-protege.ttl
> +:BlackHoleRoute a :BlackHoleRoute,
yeah I agree that "BlackHoleRoute" might be too specific for a technique, will broaden the scope...

2024-08-16 16:15 UTC, ryantxu1 commented
Before 8/16 commit:

![image](https://github.com/user-attachments/assets/81a378a0-73a8-4e9c-91c2-8f26f4374f67)

After:

![image](https://github.com/user-attachments/assets/299f3374-2f8e-482f-8680-fda4bd2475d5)


**Notes**
- Added _Session Termination_ and _Takedown Domain Registration_ techniques latter courtesy of #199 
- Deleted Black Hole Route
  - Blackholing and its cousin sinkholing are captured by DNS Denylisting
 - Deleted Network Eviction
   - Given the matrix heuristics, there's not enough techniques that fall under that currently, so Flush DNS Cache and Takedown Domain Registration are moved to object eviction. (The definition of Evict still covers 'network')
   
 @netfl0 Please review

2024-08-16 16:18 UTC, ryantxu1 commented
I could see Rogue Device Removal as a possible addition... @apapaa do you have any further details or references on this?

2024-08-16 16:24 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +    rdfs:subClassOf :AccessEviction ;
this doesn't seem right, AccessMediator is a type of DA in the current model. Not a technique.

2024-08-16 16:30 UTC, ryantxu1 commented on src/ontology/d3fend-protege.ttl
> +    rdfs:subClassOf :AccessEviction ;
Oh, thats strange, I didn't make that change manually - I agree though, will revert

2024-08-19 12:50 UTC, ryantxu1 commented on src/ontology/d3fend-protege.ttl
> +    rdfs:subClassOf :AccessEviction ;
@netfl0 Upon further review, I don't think Access Mediator was actually changed. The line refers to Credential Eviction becoming a subclass of Access Eviction lol

2024-08-19 15:12 UTC, netfl0 commented
Edits:

- [ ] Drop "suspicious" from unenroll; more importantly MFA Token Disenrollment 
- [ ] Move process Eviction & Credential back up, and reassociate with tactic
- [ ] Move Delete User account to Object Eviction
   - [ ]  User Account Deletion versus Delete User
- [ ] Move Session Termination to Process Eviction
- [ ] Delete Access Eviction; bring back it later as we expand IAM modeling
- [ ] instead, Domain Registration Takedown
- [ ] DNS Cache Eviction
- [ ] Registry Key Deletion

2024-08-19 18:07 UTC, apapaa commented
> Edits:
> 
> * [x]  Drop "suspicious" from unenroll; more importantly MFA Token Disenrollment
> * [x]  Move process Eviction & Credential back up, and reassociate with tactic
> * [x]  Move Delete User account to Object Eviction
>   
>   * [x]   User Account Deletion versus Delete User
> * [x]  Move Session Termination to Process Eviction
> * [x]  Delete Access Eviction; bring back it later as we expand IAM modeling
> * [x]  instead, Domain Registration Takedown
> * [ ]  DNS Cache Eviction
> * [ ]  Registry Key Deletion

@ryantxu1  and @netfl0 
Agree with "Domain Registration Takedown" wording. Could also add the following:
- "Service Takedown" - related to takedown requests that could be sent to abuse notification emails for hosting providers, DNS providers and SaaS providers

2024-08-19 19:30 UTC, ryantxu1 commented
Post restructure:

![image](https://github.com/user-attachments/assets/0d9b3392-4e25-4266-855e-0316107534de)

2024-08-19 20:49 UTC, apapaa commented
> Post restructure:
> 
> ![image](https://private-user-images.githubusercontent.com/33180883/359221593-0d9b3392-4e25-4266-855e-0316107534de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDA4MDQsIm5iZiI6MTcyNDEwMDUwNCwicGF0aCI6Ii8zMzE4MDg4My8zNTkyMjE1OTMtMGQ5YjMzOTItNGUyNS00MjY2LTg1NWUtMDMxNjEwNzUzNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIwNDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZDkzNjcwNzZhN2Y5YzkxMzU4NGM4NmZkNWFhNjNkMWE3YzkyZDgxNmU1OGQ4YjNmMzliNjdjZmNhN2NjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OsSF8HWRTp0BgysupZJr_haERyzhWjMK8L-lr57SOFE)

Is Revocation a better word than Disenrollment under "MFA Token Disenrollment"

2024-08-21 15:41 UTC, netfl0 commented
> > Post restructure:
> > ![image](https://private-user-images.githubusercontent.com/33180883/359221593-0d9b3392-4e25-4266-855e-0316107534de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDA4MDQsIm5iZiI6MTcyNDEwMDUwNCwicGF0aCI6Ii8zMzE4MDg4My8zNTkyMjE1OTMtMGQ5YjMzOTItNGUyNS00MjY2LTg1NWUtMDMxNjEwNzUzNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIwNDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZDkzNjcwNzZhN2Y5YzkxMzU4NGM4NmZkNWFhNjNkMWE3YzkyZDgxNmU1OGQ4YjNmMzliNjdjZmNhN2NjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OsSF8HWRTp0BgysupZJr_haERyzhWjMK8L-lr57SOFE)
> 
> Is Revocation a better word than Disenrollment under "MFA Token Disenrollment"

I think so. I think we're trying to avoid the notion of getting it physically returned. However, CRLs use the same terminology. In D3FEND 1.0 we should also change CredentialRevoking to CredentialRevocation . cc @hack-sentinel

2024-08-22 13:07 UTC, ryantxu1 commented
Renaming complete

2024-08-22 13:49 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> -:CredentialRevoking a :CredentialRevoking,
I meant to do this in the future, but we can use this as a case study to test out our deprecation strategy. cc @hack-sentinel

2024-09-13 13:22 UTC, ryantxu1 commented
Are there any other changes needed before this is pushed? @netfl0

2024-09-13 14:16 UTC, ryantxu1 commented
@netfl0  is there anything else to be done before merging?

2024-09-13 15:41 UTC, ryantxu1 commented
![image](https://github.com/user-attachments/assets/758f5420-0017-44a3-93a8-ea7f927f8942)

2024-09-13 15:57 UTC, apapaa commented
I think it looks good @ryantxu1
@netfl0 could you please consider adding me as a Contributor when this goes live?

2024-09-13 22:08 UTC, netfl0 approved these changes

2024-09-13 22:09 UTC, netfl0 commented
it appears there are merge conflicts, can you resolve? @ryantxu1

2024-09-19 19:51 UTC, merged