add serializes and deserializes tactical verbs to ontology
d3fend/d3fend-ontology pull request #271
Opened 2024-07-22 16:19 UTC by aamedina

- Introduce :serializes and :deserializes
- Add restrictions to :SerializationFunction and :DeserializationFunction classes that uses the verbs
- assert :encrypts as a subproperty of :serializes
- define :decrypts as a subproperty of :deserializes

Please critique/review and I'll edit accordingly!

fixes #269

2024-07-24 15:06 UTC, netfl0 requested changes
My only question is added as a comment/task to @hack-sentinel , otherwise this looks create to me.

We have issues with linking to wordnet in general since they've changed what they're hosting. We ought to create a wordnet fork, if the license permits it, and create a stable github pages site for it.

2024-07-24 15:06 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +        :serializes ;
I am 80% sure this is true, @hack-sentinel can you comment on this superproperty declaration.

2024-07-29 15:49 UTC, aamedina commented on src/ontology/d3fend-protege.ttl
> +        :serializes ;
@hack-sentinel What do you think?

2024-11-27 22:10 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +        :serializes ;
Lets flatten the superproperties to avoid confusion.

2024-12-16 17:43 UTC, closed without merging