First D3FEND-CCO mappings
d3fend/d3fend-ontology pull request #296
Opened 2024-09-17 01:40 UTC by giacomodecolle

First mappings between D3FEND and CCO, developed with @johnbeve and @Finn1928.

2024-09-18 17:31 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Sensor owl:equivalentClass cco:Sensor .
@giacomodecolle , last CCO version I checked a cco:Sensor IS A transducer versus a functional sensor, this is a big problem in my view @giacomodecolle @mark-jensen @johnbeve 

Here is how we have the taxonomy in D3FEND, this would be a proposal to refactor CCO:

![image](https://github.com/user-attachments/assets/17ad3b88-af26-4400-a589-b0e7e1dc8ae8)

2024-10-15 16:00 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:DigitalEvent rdfs:subClassOf <http://purl.obolibrary.org/obo/BFO_0000035> .
After discussion, tentatively: 

New d3f:Event class equiv to bfo:Process . 

New d3f:Action ~ cco:Act

2024-10-15 16:22 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Activity rdfs:subClassOf <http://purl.obolibrary.org/obo/BFO_0000015> .
OBE, we've deleted d3f:Activity in 0.17.0 , we can delete this.

2024-10-15 16:25 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:PhysicalObject rdfs:subClassOf <http://purl.obolibrary.org/obo/BFO_0000030>.
We now only have d3f:PhysicalArtifact d3f:PhysicalObject was deleted in 0.17.0

2024-10-15 16:29 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Technique rdfs:subClassOf cco:DirectiveInformationContentEntity.
we can now map d3f:Plan to cco:DirectiveInformationContentEntity or cco:Plan

We do not consider a Technique an Action.

2024-10-15 16:31 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:DefensiveTechnique rdfs:subClassOf cco:DirectiveInformationContentEntity.
OBE no longer needed

2024-10-15 16:31 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:OffensiveTechnique rdfs:subClassOf cco:DirectiveInformationContentEntity.
OBE no longer needed

2024-10-15 16:32 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Log rdfs:subClassOf cco:InformationContentEntity .
we have modeled log as a bearing entity.

We have also modeled record as a bearing entity but this is debatable.

2024-10-15 16:34 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Artifact rdfs:subClassOf <http://purl.obolibrary.org/obo/BFO_0000002> .
Needs to be revisited:

![image](https://github.com/user-attachments/assets/5e5fea60-9adb-4d32-b4aa-9d0f138e8ab2)

2024-10-15 16:39 UTC, netfl0 requested changes

2024-10-15 16:39 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:AnalysisOfAlternatives rdfs:subClassOf cco:Act .
Correct but i think cco has something more specific

2024-10-15 16:39 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:JobSchedule rdfs:subClassOf cco:Plan .
This isn't going to make a problem, but its hard to imagine a reasonable use case for this.

2024-10-15 16:40 UTC, netfl0 commented
- [ ] Make sure to merge in d3fend develop to pull in 0.17.0

2024-11-12 22:04 UTC, giacomodecolle commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Log rdfs:subClassOf cco:InformationContentEntity .
I have been thinking about some of the content/bearing entity distinctions. Despite what some classes in CCO and C3O do, if something doesn't have properties like weight and spatial extension, I think it should go under the content entity part of the hierarchy. Perhaps a discussion for a future meeting.

2024-11-12 22:23 UTC, giacomodecolle commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Sensor owl:equivalentClass cco:Sensor .
Will bring this discussion to Mark and John eventually, I am taking the equivalence out for the moment

2024-11-14 17:29 UTC, giacomodecolle commented
I went through comments from last meeting and updated to new CCO identifiers. Apologies for the three commits, there was something messed up on my end of things. By next meeting, I will work on some new mappings for the remaining core classes.

2024-11-20 13:02 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +#cco org/ont00000974 is cco Plan.
In the new version of D3FEND Core we have Plan. It may make sense to just map d3f:Plan to cco:Plan.

We make a distinction between technique and procedure, both we've categorized as plans. Technique is a less defined type of plan than procedure. Like a meta-plan if that makes sense.

We're trying to disambiguate some terminology which has military roots: Tactics, Techniques, and Procedures.

2024-11-20 13:11 UTC, netfl0 requested changes

2024-11-20 13:11 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +     owl:imports <https://raw.githubusercontent.com/CommonCoreOntology/CommonCoreOntologies/refs/tags/v1.6-2024-09-26/src/cco-merged/CommonCoreOntologiesMerged.ttl> .
can we set this back to 1.7?

2024-11-20 13:11 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +#cco ont00000974 is ccoPlan .
It is true that this is a type of Plan, but it is also a Schedule of Plans which indicates very specific intervals of plan execution. I am not suggesting a change here at the moment but making some distinctions here could be useful in the future for systems analysis use cases.

2024-11-24 00:46 UTC, giacomodecolle commented on src/ontology/mappings/d3fend-cco.ttl
> +     owl:imports <https://raw.githubusercontent.com/CommonCoreOntology/CommonCoreOntologies/refs/tags/v1.6-2024-09-26/src/cco-merged/CommonCoreOntologiesMerged.ttl> .
Actually, shouldn't we be moving to 2.0?

2024-11-24 03:59 UTC, giacomodecolle commented on src/ontology/mappings/d3fend-cco.ttl
> +#cco ont00000974 is ccoPlan .
In CCO, I would say that a job schedule prescribes a series of processes which are themselves in turn prescribed by other plans. I should be able to make this work in the mappings through some logic, without needing to change CCO or D3FEND.

2024-12-12 16:58 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:DigitalArtifact rdfs:subClassOf <http://purl.obolibrary.org/obo/BFO_0000002> .
point of discussion

2024-12-18 16:54 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:DigitalArtifact rdfs:subClassOf <http://purl.obolibrary.org/obo/BFO_0000002> .
Decision to keep mapping to Continuant.

2024-12-18 17:02 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:System owl:equivalentClass [ owl:intersectionOf ( <http://purl.obolibrary.org/obo/BFO_0000027>
convert to sublcass of rather than equiv...

2024-12-18 17:11 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:DigitalEvent rdfs:subClassOf [ owl:intersectionOf ( <http://purl.obolibrary.org/obo/BFO_0000015>
add we mean both ICE and IBA

2024-12-18 17:16 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +# d3f:Execution rdfs:subClassOf <http://purl.obolibrary.org/obo/BFO_0000015> .
there is no d3f:Execution

2024-12-18 17:17 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:InformationContentEntity owl:equivalentClass <https://www.commoncoreontologies.org/ont00000958> .
d3f:InformationContentEntity will be deprecated, please remove this line.

2024-12-18 17:19 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Log rdfs:subClassOf <https://www.commoncoreontologies.org/ont00000958> .
Log should be a bearer

2024-12-18 17:22 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Capability owl:equivalentClass <https://www.commoncoreontologies.org/ont00001379> .
Lets remove this for now. Catalog things are going to be deprecated.

2024-12-18 17:22 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:AnalysisOfAlternatives rdfs:subClassOf <https://www.commoncoreontologies.org/ont00000228> .
Lets remove this for now. Catalog things are going to be deprecated.

2024-12-18 17:22 UTC, netfl0 commented on src/ontology/mappings/d3fend-cco.ttl
> +d3f:Assessment rdfs:subClassOf <https://www.commoncoreontologies.org/ont00000636> .
Lets remove this for now. Catalog things are going to be deprecated.

2024-12-18 22:00 UTC, netfl0 approved these changes

2024-12-18 22:00 UTC, merged