Added Upper Model of OT Artifacts
d3fend/d3fend-ontology pull request #329
Opened 2024-12-13 15:44 UTC by OG3x100

2024-12-13 17:54 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +    :definition "An OT Actuation device is a device capable of TCP/IP communication, has firmware and controls an OT Actuator." ;
remote TCP/IP from definition

2024-12-17 18:23 UTC, netfl0 commented
@aamedina can you give this a review / check?

2024-12-17 21:19 UTC, netfl0 commented on src/ontology/d3fend-protege.ttl
> +    :definition "In the broadest definition, a sensor is a device, module, machine, or subsystem that detects events or changes in its environment and sends the information to other electronics, freq
This is not good, please remove.

2024-12-17 21:34 UTC, merged

2024-12-17 21:43 UTC, aamedina requested changes

2024-12-17 21:43 UTC, aamedina commented on src/ontology/d3fend-protege.ttl
> +:OTPowerSupply a owl:Class ;
I think we need a d3f:PowerSupply artifact that an OT Power Supply is a specialization of.

2024-12-17 21:43 UTC, aamedina commented on src/ontology/d3fend-protege.ttl
> +:communicates-with a owl:ObjectProperty ;
I think this is a owl:SymmetricProperty, where if x communicates with y then y also communicates with x. Otherwise, perhaps the d3f:connects property is sufficient.

2024-12-17 21:43 UTC, aamedina commented on src/ontology/d3fend-protege.ttl
> +:controls a owl:ObjectProperty ;
I think ideally this would be a superproperty of d3f:manages, but I can see why you didn't choose that as the definition there is too specific to relating some thing x to a digital artifact y. 

d3f:manages rdfs:subPropertyOf d3f:controls makes sense to me. 

I think we should also add the inverse property (d3f:controlled-by).

2024-12-17 21:43 UTC, aamedina commented on src/ontology/d3fend-protege.ttl
> +:powered-by a owl:ObjectProperty ;
I think this is a subproperty of d3f:dependsOn, and also needs an inverse (d3f:powers).